/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gjx.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.gjx.jxufe.factory.Factory;
import com.gjx.jxufe.vo.InformationType;
import com.gjx.struts.form.InformationTypeForm;
import com.gjx.util.Constants;

public class InformationTypeAction extends DispatchAction {
	private static final Log logger = LogFactory.getLog(InformationTypeAction.class);

	// 插入
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String name = ((InformationTypeForm) form).getName();
		logger.info("插入的新类型为：" + name);

		InformationType informationType = new InformationType();
		informationType.setName(name);
		Factory.getInformationTypeDaoImpl().insertInformationType(informationType);
		List list = Factory.getInformationTypeDaoImpl().getInformationTypeList();
		request.setAttribute(Constants.INFORMATION_TYPE_LIST, list);

		return mapping.findForward(Constants.SUCCESS_KEY);
	}

	// 读取
	public ActionForward read(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List list = Factory.getInformationTypeDaoImpl().getInformationTypeList();
		request.setAttribute(Constants.INFORMATION_TYPE_LIST, list);

		return mapping.findForward(Constants.SUCCESS_KEY);
	}

	// 更新
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		int id = Integer.parseInt(request.getParameter("id"));
		String name = ((InformationTypeForm) form).getName();
		InformationType informationType = Factory.getInformationTypeDaoImpl().getInformationType(id);
		informationType.setName(name);
		logger.info("更新类型名称为：" + name);
		Factory.getInformationTypeDaoImpl().updateInformationType(informationType);
		List list = Factory.getInformationTypeDaoImpl().getInformationTypeList();
		request.setAttribute(Constants.INFORMATION_TYPE_LIST, list);

		return mapping.findForward(Constants.SUCCESS_KEY);
	}

	// 删除
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id = Integer.parseInt(request.getParameter("id"));
		Factory.getInformationTypeDaoImpl().deleteInformationType(id);
		List list = Factory.getInformationTypeDaoImpl().getInformationTypeList();
		request.setAttribute(Constants.INFORMATION_TYPE_LIST, list);
		logger.info("删除一条类型记录成功" + id);
		return mapping.findForward(Constants.SUCCESS_KEY);
	}

	// 取得一个link的类型
	public ActionForward getInformationType(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id=Integer.parseInt(request.getParameter("id"));
		logger.info("找到要更改的LinkType的ID:"+id);
		InformationType informationType=Factory.getInformationTypeDaoImpl().getInformationType(id);
		List list = Factory.getInformationTypeDaoImpl().getInformationTypeList();
		request.setAttribute(Constants.INFORMATION_TYPE_LIST, list);
		request.setAttribute("informationType", informationType);
		return mapping.findForward(Constants.SUCCESS_KEY);
	}
}