/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gjx.struts.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.gjx.jxufe.factory.Factory;
import com.gjx.jxufe.vo.Account;
import com.gjx.struts.form.LoginForm;
import com.gjx.util.Constants;


public class LoginAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm lf = (LoginForm) form;// TODO Auto-generated method stub

		Account ac = Factory.getAccountDaoImpl().getAccount(lf.getUserId(),
				lf.getPassword());
		if (null != ac) {
			HttpSession session = request.getSession();
			session.setAttribute(Constants.ADMIN_KEY, ac);
		} else {
			ActionMessages errors = new ActionMessages();
			errors.add("errors",
					new ActionMessage("invalidate.userId.password"));
			this.saveErrors(request, errors);

			return mapping.getInputForward();
		}
	   
		return mapping.findForward("admin");
		
	}
}