/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gjx.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gjx.jxufe.factory.Factory;
import com.gjx.util.Constants;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2007
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ReadJpkcAction extends Action {
	private static final Log logger = LogFactory.getLog(ReadJpkcAction.class);
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int level=1;
		try{
			level=Integer.parseInt(request.getParameter("level"));
		}catch(Exception e){
			level=0;
		}
		if(level==0){
			List list = Factory.getJpkcDaoImpl().getJpkcList(3);		
			request.setAttribute(Constants.JPKC_LIST, list);
			request.setAttribute("level", level);
			return mapping.findForward(Constants.SUCCESS_KEY);
		}
		List list = Factory.getJpkcDaoImpl().getJpkcList(level);		
		request.setAttribute(Constants.JPKC_LIST, list);
		request.setAttribute("level", level);
		return mapping.findForward(Constants.SUCCESS_KEY);

	}
}