/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gjx.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.gjx.jxufe.factory.Factory;
import com.gjx.jxufe.vo.Information;
import com.gjx.jxufe.vo.InformationType;
import com.gjx.util.Constants;

public class ReadInformationAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String strPageNum = request.getParameter("pageNum");
		String strClassify = request.getParameter("classify");
		int id = 0;
		int pageNum = 0;
		int classify = 0;
		if (null != strPageNum && !"".equals(strPageNum)) {
			try {

				pageNum = Integer.parseInt(strPageNum);
			} catch (NumberFormatException nfe) {
				pageNum = 0;

			}
		}
		if (null != strClassify && !"".equals(strClassify)) {
			try {
				classify = Integer.parseInt(strClassify);
				id = Integer.parseInt(request.getParameter("id"));
			} catch (NumberFormatException nfe) {
				id = 0;
				classify = 0;
			}

		}
		if(id==0&&classify==0){
			try {
				classify = Integer.parseInt(strClassify);
			} catch (NumberFormatException nfe) {
				classify = 0;
			}
			List list = Factory.getInfromationDaoImple().getInformationList(
					request, pageNum, Constants.MORE_INORMATION_PAGE_LENGTH,classify);
			InformationType ifType=Factory.getInformationTypeDaoImpl().getInformationType(classify);
						
			request.setAttribute(Constants.INFORMATION_LIST, list);
			request.setAttribute(Constants.INFORMATION_TYPE, ifType);
			
			List informationMenuList=Factory.getInfromationDaoImple().getInformationList(
					request, 0, Constants.MORE_INORMATION_PAGE_LENGTH, classify);
					request.setAttribute("informationMenuList", informationMenuList);
			
			return mapping.findForward("moreInformationList");
		}else{
			
		List list = Factory.getInfromationDaoImple().getInformationList(
				request, pageNum, Constants.INFORMATION_PAGE_LENGTH, classify);
		Information information = Factory.getInfromationDaoImple()
				.getInformation(id);
		InformationType informationType = Factory.getInformationTypeDaoImpl().getInformationType(classify);
		request.setAttribute(Constants.INFORMATION_TYPE, informationType);
		request.setAttribute(Constants.INFORMATION_KEY, information);
		request.setAttribute(Constants.INFORMATION_LIST, list);
		
		List informationMenuList=Factory.getInfromationDaoImple().getInformationList(
		request, pageNum, Constants.MORE_INORMATION_PAGE_LENGTH, classify);
		request.setAttribute("informationMenuList", informationMenuList);
		
		return mapping.findForward(Constants.SUCCESS_KEY);
		}
		

	}
}