/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gjx.struts.form;

import java.util.regex.Pattern;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * MyEclipse Struts Creation date: 08-10-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="jpkcForm"
 */
public class JpkcForm extends ActionForm {	

	private String name;

	private String teacher;

	private String fullname;

	private int level;

	private int year;

	private String info;

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=null;
		if(null==name||"".equals(name)||null==fullname||"".equals(fullname)||
				null==teacher||"".equals(teacher)){
			errors=new ActionErrors();
			errors.add("error", new ActionMessage("except.desc.null"));
		}
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.setFullname(null);
		this.setInfo(null);
		this.setLevel(2);
		this.setName(null);
		this.setTeacher(null);
		this.setYear(2007);
		
	}

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getInfo() {
		if(null!=info){
			System.out.println(info);
		    info=Pattern.compile("\r\n").matcher(info).replaceAll("<br>");
		    info=Pattern.compile("\n").matcher(info).replaceAll("<br>");
			System.out.println(info);
		}
		return info;
	}

	public void setInfo(String info) {		
		this.info = info;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTeacher() {
		return teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

}