/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.gjx.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.gjx.jxufe.factory.Factory;
import com.gjx.util.Constants;

public class LinkForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** typeid property */
	private int typeid;

	/** image property */
	private String image;

	/** url property */
	private String url;

	/** name property */
	private String name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=new ActionErrors();
		
		List list=Factory.getLinkTypeDaoImpl().getLinkTypeList();
		request.setAttribute(Constants.LINK_TYPE_LIST, list);
		if(null==this.url||this.url.length()<4){
			errors.add("error",new ActionMessage("url.invalidate"));
		}
		if(null==this.name||this.name.length()<2){
			errors.add("error",new ActionMessage("link.name.invalidate"));
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the typeid.
	 * @return String
	 */
	public int getTypeid() {
		return typeid;
	}

	/** 
	 * Set the typeid.
	 * @param typeid The typeid to set
	 */
	public void setTypeid(int typeid) {
		this.typeid = typeid;
	}

	/** 
	 * Returns the image.
	 * @return String
	 */
	public String getImage() {
		return image;
	}

	/** 
	 * Set the image.
	 * @param image The image to set
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/** 
	 * Returns the url.
	 * @return String
	 */
	public String getUrl() {
		return url;
	}

	/** 
	 * Set the url.
	 * @param url The url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
}